# Generated by Django 6.0.5 on 2026-05-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=10)),
                ('weight', models.FloatField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feedback', models.TextField()),
                ('date_of_birth', models.DateField(auto_now=True)),
                ('date_of_birth_with_time', models.DateTimeField(auto_now=True)),
                ('birth_time', models.TimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
