# Generated by Django 6.0.5 on 2026-05-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
