# Generated by Django 6.0.5 on 2026-06-24 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_ranksheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='student_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.student'),
        ),
    ]
