# Generated by Django 6.0.5 on 2026-06-24 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0006_task_student_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='student_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_task', to='Students.student'),
        ),
    ]
